name: Deploy

on: [push,pull_request]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
<<<<<<< HEAD:.github/workflows/deploy.yml
  buildWebGL:
    name: Build for WebGL
=======
  build:
    name: Deploy
>>>>>>> 2f611c4095fbe6afa0e6c2fe7844d91a9fb9f51b:.github/workflows/main.yml
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      - name: Restore Library cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-build-WebGL
          restore-keys: |
<<<<<<< HEAD:.github/workflows/deploy.yml
            Library-build-
            Library-

      - uses: game-ci/unity-builder@v2
=======
            Library-

      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
>>>>>>> 2f611c4095fbe6afa0e6c2fe7844d91a9fb9f51b:.github/workflows/main.yml
        with:
          targetPlatform: WebGL
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-WebGL
          path: build/WebGL
      
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build-WebGL
          path: build

<<<<<<< HEAD:.github/workflows/deploy.yml
      - uses: actions/upload-artifact@v2
        with:
          name: build-WebGL
          path: build/WebGL

  deployPages:
    needs: buildWebGL
    name: Deploy to Github Pages 🚀
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: build-WebGL
          path: build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build/WebGL
=======
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build/WebGL
          commit-message: Deploy
          single-commit: true
>>>>>>> 2f611c4095fbe6afa0e6c2fe7844d91a9fb9f51b:.github/workflows/main.yml
